name: Java Maven CICD

on:
  push: 
    branches: 
      - master 
  pull_request: 
    branches: 
      - master 

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Se deplacer en repository 
        uses: actions/checkout@v3 

      - name: Faire Java et Maven 
        uses: actions/setup-java@v3 
        with: 
          distribution: 'temurin' 
          java-version: '11' 
          cache: 'maven'

      

      - name: Maven
        run: mvn clean install

      - name: Faire les tests
        run: mvn test

      - name: Archiver les Tests 
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-resultats
          path: target/surefire-reports/*.xml
