name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Maven
      - name: Set up Maven
        uses: s4u/setup-maven@v2
        with:
          maven-version: '3.9.5' # Spécifie la version exacte de Maven à installer
          settings-path: '.github/maven' # Optionnel, si tu veux ajouter un fichier `settings.xml`

      # Étape 3 : Configurer le JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven # Cache des dépendances Maven

      # Étape 4 : Installer les dépendances et compiler
      - name: Install dependencies and build
        run: mvn clean install -DskipTests=true

      # Étape 5 : Lancer les tests
      - name: Run tests
        run: mvn test

      # Étape 6 : Enregistrer les résultats des tests
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml
