name: Java Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Maven
      - name: Set up Maven
        uses: s4u/setup-maven@v2
        with:
          maven-version: '3.9.5' # Spécifie la version exacte de Maven à installer
          

      # Étape 3 : Configurer le JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven 

      - name: Install dependencies and build
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml
